name: Compile CLEO Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Compile
        run: |
          npx -p @sannybuilder/cli sanny compile SA.FirstPerson.txt --output SA.FirstPerson.csi --game sa_mobile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cleo-compiled
          path: SA.FirstPerson.csi
